databases:
  - name: searchbox
    databaseName: searchbox
    user: searchbox
    plan: free

services:
  - type: web
    name: searchbox
    runtime: ruby
    plan: free
    buildCommand: yarn install && bundle install && yarn run webpack && bundle exec rake assets:precompile
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: searchbox
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2